name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          brew update
          brew tap homebrew/cask

      - name: Install
        run: brew install --formula --build-from-source Formula/*.rb

      - name: Test
        run: brew test Formula/*.rb

      - name: Audit
        run: |
          brew tap-new siafoundation/test --no-git
          cp -r Formula/* $(brew --repository)/Library/Taps/siafoundation/homebrew-test/Formula
          for file in $(brew --repository)/Library/Taps/siafoundation/homebrew-test/Formula/*
          do
              brew audit --formula "$(basename ${file%.rb})"
          done
          brew untap siafoundation/test
